Fix intermittent k8s Auth
keikoproj/flippy pull request #13
Opened 2023-02-03 00:30 UTC by virajrk

Update golang - 1.19
Update Kubectl to 1.21
Add a hack to wait until kube context is set

**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Fix.
Ref - https://github.com/keikoproj/flippy/issues/12

2023-02-09 00:38 UTC, virajrk commented
Ref - https://github.com/kubernetes/kubernetes/issues/65785#issuecomment-865173559

Testing - 
Verified unit test. 
Deployed PR image to test cluster. Validated functionality.

2023-02-10 01:16 UTC, vinay-g requested changes

2023-02-10 01:16 UTC, vinay-g commented on install/startup.sh
> +kube_system_pod_count=$(kubectl get pod -n kube-system | wc -l)
this will count the header as well like use `--no-headers` to list only the pods

2023-02-10 01:16 UTC, vinay-g commented on install/startup.sh
> +max_retry_count=5
Should we make this configurable via ENV ? so we can control the delay without creating a new image

2023-02-13 18:01 UTC, vinay-g approved these changes

2023-02-13 20:02 UTC, vrushalijoshi approved these changes
looks good

2023-02-13 22:09 UTC, merged